// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Scaffolding;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TestNamespace
{
    [DbContext(typeof(CompiledModelRelationalTestBase.FunctionTypeMappingContext))]
    public partial class FunctionTypeMappingContextModel : RuntimeModel
    {
        private static readonly bool _useOldBehavior31751 =
            System.AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue31751", out var enabled31751) && enabled31751;

        static FunctionTypeMappingContextModel()
        {
            var model = new FunctionTypeMappingContextModel();

            if (_useOldBehavior31751)
            {
                model.Initialize();
            }
            else
            {
                var thread = new System.Threading.Thread(RunInitialization, 10 * 1024 * 1024);
                thread.Start();
                thread.Join();

                void RunInitialization()
                {
                    model.Initialize();
                }
            }

            model.Customize();
            _instance = (FunctionTypeMappingContextModel)model.FinalizeModel();
           OnModelFinalized(_instance);
        }

        private static FunctionTypeMappingContextModel _instance;
        public static IModel Instance => _instance;

        static partial void OnModelFinalized(IModel model);

        partial void Initialize();

        partial void Customize();
    }
}
